class BaldMan < HumanoidNpc
  LABEL  = 'Kale man'
  REWARD = 1
  LINES = {
    angry: [
      'GODVERDOMME!',
      'GODVERDEGODVERDEGODVERDEKANKER!',
      'GODSAMMEKRAKEN! KIJK UIT, KANKERLIJER!',
      'GODVER! MIJN HEUP! MIJN TYFUSHEUP!',
      'GODVERDOMME NOG AAN TOE, KUTLUL!',
      'GODVER! GODVER! GODVER! KANKER!',
      'GODVERDOMME, WAT EEN ACHTERLIJKE KANKERSUKKEL!',
      'GODVERDOMME! DAT IS TOCH NIET NORMAAL MEER, HOERENZOON!',
      'GODVERDOMME, MIJN KALE KOP! MIJN KANKERKOP!',
      'GODVERDOMSE KUTPANDA! IK SLA JE TERINGAUTO IN PUIN!',
      'GODVERDOMME! IK VERMOORD JE, KANKERHOND!',
      'GODVER! KOM HIER, DAN TREK IK JE KUTKOP ERAF!',
      'JEETJE WAT EEN STANK HIER ZEG!'
    ]
  }

  def chatty?(game)
    player = game.nearest_player(x, z, 12)
    player && player.car.speed.abs > 6
  end
end

class BaldFlag < BaldMan
  LABEL = 'Kale man met Brabantse vlag'
  TTS_VOICE = 'nl-BE-ArnaudNeural'
  LINES = {
    angry: [
      'GODVERDOMME! WA DOEDE GIJ NOU, KAOIE KANKERHOND!',
      'KÈK UIT, GODVERDOMME! KAOIE TERINGLIJER!',
      'GE ZIJT NIE GOE WIJS, GODVERDOMSE KUTLUL!',
      'GODVERDOMME! MÈN VLAG! GE HEBT MÈN VLAG KAPOTGEREDEN, KANKERZAK!',
      'HEDDE GIJ WEL GEKEKEN, GODVERDOMSE TYFUSSUKKEL!',
      'GODVERDOMME! DA KEN TOCH NIE, KUTJONG!',
      'HOUDOE EN BEDANKT, GODVERDOMSE KLOOTZAK!',
      'GODVER! GE RIJDT OVER MÈN TENEN, KANKERLUL!',
      'GODVERDOMME, GIJ KAOIE KUTPANDA!',
      'WA IS DA NOU WIR, GODVERDOMME! IK SLA JE KANKERPLAT!',
      'GODVER! IK ZEG \'T TEGEN ONS MOEDER, EN DIE MAAKT JE KANKERAF!',
      'KOM HIER, JONGUH! DAN KRÈGDE GIJ EEN LEL OP JE KUTBAKKES!'
    ]
  }
end
